/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tqa.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tqa.dao.PerformanceDAO;
import tqa.dao.QuestionDAO;
import tqa.pojo.Answer;
import tqa.pojo.AnswerStore;
import tqa.pojo.Exam;
import tqa.pojo.Performance;
import tqa.pojo.QuestionStore;
import tqa.pojo.Questions;
import tqa.pojo.UserProfile;

/**
 *
 * @author lenovo
 */
public class TakeTestFrame extends javax.swing.JFrame {
        private Exam newExam;
        private QuestionStore qstore;
        private AnswerStore astore;
        private int pos,qno =0;
    /**
     * Creates new form TakeTestFrame
     */
    public TakeTestFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jlb1.setText("HELLO \t"+UserProfile.getUsername());
        qstore = new QuestionStore();
        astore = new AnswerStore();
        qno = 1;
        jlbQno.setText("Question \t"+qno );
    }
    public TakeTestFrame(Exam newExam)
    {
        this();
        this.newExam = newExam;
        jlbTitle.setText(newExam.getLanguage().toString().toUpperCase()+" \t PAPER");
        loadQuestions();
        showQuestions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlb1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jlbQno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaQuestion = new javax.swing.JTextArea();
        jrbOption1 = new javax.swing.JRadioButton();
        jrbOption2 = new javax.swing.JRadioButton();
        jrbOption3 = new javax.swing.JRadioButton();
        jrbOption4 = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        mage = new javax.swing.JLabel();
        jlbTitle = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlb1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlb1.setForeground(new java.awt.Color(240, 240, 240));

        jlbQno.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jlbQno.setForeground(new java.awt.Color(240, 240, 240));

        jtaQuestion.setColumns(20);
        jtaQuestion.setRows(5);
        jScrollPane1.setViewportView(jtaQuestion);

        jrbOption1.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(jrbOption1);

        jrbOption2.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(jrbOption2);

        jrbOption3.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(jrbOption3);

        jrbOption4.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(jrbOption4);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        mage.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\Java Workshop\\Project Notes\\project-images\\good luck2.jpg")); // NOI18N

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(image)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbQno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jrbOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNext))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addComponent(jrbOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(30, 30, 30)
                                .addComponent(btnDone)))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(image)
                    .addComponent(jlb1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jlbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(mage)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbQno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOption2)
                    .addComponent(jrbOption1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOption4)
                    .addComponent(jrbOption3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious)
                    .addComponent(btnCancel)
                    .addComponent(btnDone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String chosenAnswer = getUserAnswer();
        if(chosenAnswer != null)
        {
            Questions question = qstore.getQuestion(pos);
            String correctAnswer = question.getCorrectAnswer();
            Answer newanswer = new Answer(newExam.getExamid(),newExam.getLanguage() , qno, chosenAnswer, correctAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if(answer == null)
            {
                astore.addAnswer(newanswer);
            }
            else
            {
                if(newanswer.getChosenAnswer().equals(answer.getCorrectAnswer()) == false)
                {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newanswer);
                }
            }
        }
            pos++;
            if(pos >= qstore.getCount())
                pos = 0;
            qno++;
            if(qno > qstore.getCount())
            {
                qno = 1;
                JOptionPane.showMessageDialog(null,"This is final question of the test. \n Click on DONE button to submit the test.", "Submit!!", JOptionPane.INFORMATION_MESSAGE);
            }
            showQuestions();
            jlbQno.setText("Question No "+qno);
            System.out.println(pos+"yaha");
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        String chosenAnswer = getUserAnswer();
        if(chosenAnswer != null)
        {
            Questions question = qstore.getQuestion(pos);
            String correctAnswer = question.getCorrectAnswer();
            Answer newanswer = new Answer(newExam.getExamid(),newExam.getLanguage() , qno, chosenAnswer, correctAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if(answer == null)
            {
                astore.addAnswer(newanswer);
            }
            else
            {
                if(newanswer.getChosenAnswer().equals(answer.getCorrectAnswer()) == false)
                {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newanswer);
                }
            }
        }
            pos--;
            if(pos < 0)
            {
                pos = qstore.getCount()-1;
            }
                
            qno--;
            if(qno <= 0)
                qno = qstore.getCount();
            showQuestions();
            jlbQno.setText("Question No "+qno);
            
               
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String chosenAnswer = getUserAnswer();
        if(chosenAnswer != null)
        {
            Questions question = qstore.getQuestion(pos);
            String correctAnswer = question.getCorrectAnswer();
            Answer newanswer = new Answer(newExam.getExamid(),newExam.getLanguage() , qno, chosenAnswer, correctAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if(answer == null)
            {
                astore.addAnswer(newanswer);
            }
            else
            {
                if(newanswer.getChosenAnswer().equals(answer.getCorrectAnswer()) == false)
                {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newanswer);
                }
            }
        }
        int right = 0, wrong = 0;
        for(Questions que : qstore.getAllQuestion())
        {
            int qno = que.getQno();
            
            Answer answer = astore.getAnswerByQno(qno);
            if(answer == null)
                continue;
            else
            {
                String chosenAnswer1 = answer.getChosenAnswer();
                String correctAnswer = answer.getCorrectAnswer();
                if(chosenAnswer1.equals(correctAnswer))
                    ++right;
                else
                    ++wrong;
            }
        }
        String reportCard = "Total Questions : "+qstore.getCount();
        reportCard += "\n Right Answers : "+right;
        reportCard +="\n Wrong Answes : "+wrong;
        reportCard +="\n UnAttempted Answes : "+(qstore.getCount()-(right + wrong));
        JOptionPane.showMessageDialog(null,reportCard,"Here Is Your Result",JOptionPane.INFORMATION_MESSAGE);
        try
        {
            Performance performance = new Performance(UserProfile.getUsername(),newExam.getExamid(), right, wrong, (qstore.getCount()-(right + wrong)),(double)right/qstore.getCount()*100, newExam.getLanguage());
            PerformanceDAO.addPerformance(performance);
            JOptionPane.showMessageDialog(null,"Your Performance has been successfully added to the database","Performance Added",JOptionPane.INFORMATION_MESSAGE);
            PaperSelectionFrame pf = new PaperSelectionFrame();
            pf.setVisible(true);
            this.dispose();
        }
        catch(SQLException sq)
        {
            JOptionPane.showMessageDialog(null, ""+sq, "ERROR!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        PaperSelectionFrame pf = new PaperSelectionFrame();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }
    
    public void loadQuestions()
    {
        try
        {
            ArrayList<Questions> questionList = QuestionDAO.getQuestionsByExamId(newExam.getExamid());
            for(Questions obj : questionList)
            {
                qstore.addQuestion(obj);
            }
        }
        catch(SQLException sq)
        {
            JOptionPane.showMessageDialog(null,sq,"ERROR", JOptionPane.ERROR_MESSAGE);
            sq.printStackTrace();
        }
    }
    public void showQuestions()
    {
        Questions question = qstore.getQuestion(pos);
        buttonGroup1.clearSelection();
        jtaQuestion.setText(question.getQuestions());
        jrbOption1.setText(question.getAnswer1());
        jrbOption2.setText(question.getAnswer2());
        jrbOption3.setText(question.getAnswer3());
        jrbOption4.setText(question.getAnswer4());
        Answer answer =astore.getAnswerByQno(qno);
        if(answer==null)
            return;
        String chosenAnswer=answer.getChosenAnswer();
        switch(chosenAnswer){
        case "Answer1":
            jrbOption1.setSelected(true);
            break;
        case "Answer2":
            jrbOption2.setSelected(true);
            break;
        case "Answer3":
            jrbOption3.setSelected(true);
            break;
        case "Answer4":
            jrbOption4.setSelected(true);
            break;
        }
    }
    private String getUserAnswer()
    {
        if(jrbOption1.isSelected())
            return "Answer1";
        else if(jrbOption2.isSelected())
            return "Answer2";
        else if(jrbOption3.isSelected())
            return "Answer3";
        else if(jrbOption4.isSelected())
            return "Answer4";
        else
            return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlbQno;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JRadioButton jrbOption1;
    private javax.swing.JRadioButton jrbOption2;
    private javax.swing.JRadioButton jrbOption3;
    private javax.swing.JRadioButton jrbOption4;
    private javax.swing.JTextArea jtaQuestion;
    private javax.swing.JLabel mage;
    // End of variables declaration//GEN-END:variables
}
